package com.example.lenovo.h1705a_qizhongtest;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.lenovo.h1705a_qizhongtest.bean.SQL;

import com.example.lenovo.h1705a_qizhongtest.SQLDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sQLDaoConfig;

    private final SQLDao sQLDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sQLDaoConfig = daoConfigMap.get(SQLDao.class).clone();
        sQLDaoConfig.initIdentityScope(type);

        sQLDao = new SQLDao(sQLDaoConfig, this);

        registerDao(SQL.class, sQLDao);
    }
    
    public void clear() {
        sQLDaoConfig.clearIdentityScope();
    }

    public SQLDao getSQLDao() {
        return sQLDao;
    }

}
